### ISSUE TITLE
Relicense to Free BSD license

### ISSUE THREAD

**Issue by huayra** [brandonwamboldt/varnish-dashboard#1]
Hey Brandon,

Could you please relicense your code under FreeBSD so that it has the same license as the vagent2 and Varnish Cache? MIT is compatible, but it is so much easier to just have the actual same license for many reasons.

License examples:
https://github.com/varnish/vagent2/blob/master/LICENSE
https://github.com/varnish/Varnish-Cache/blob/master/LICENSE

Best, Rubén.

**Comment by brandonwamboldt** [comment]
I'll have to look into the FreeBSD license first. I don't use certain licenses (E.g. GPL) because I don't like silly restrictions on the use of my software.

**Comment by huayra** [comment]
The are both "permissive" licenses: http://opensource.org/faq#permissive

And even if they are permissive, they (both X11/MIT and FreeBSD) are also compatible with GPL: http://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses

The idea is to be able to have the option to reuse all or some of your work in the UI the agent ships with by default.

**Comment by brandonwamboldt** [comment]
Done
