### ISSUE TITLE
stat() was not happy

### ISSUE THREAD

**Issue by sz00gun** [brandonwamboldt/varnish-dashboard#2]
Can see it ( stat() was not happy ), during requesting http://<varnish_ip>:6085/html/

varnish 3.0.6 and the latest agent from Debian apt-get

any idea how to fix it?

**Comment by brandonwamboldt** [comment]
That error is a `404 Not Found` error indicating the wrong URL. Please ensure you started Varnish Agent with the correct path specified for `-H`. If the dashboard is located in `/var/www/html/varnish-dashboard`, and you specified that in the `-H` argument, the URL:

http://example.com/html/

Should work. If it does not, please ensure the file `/var/www/html/varnish-dashboard/index.html` exists. I've seen a few people who used `git checkout` wrong and had `/var/www/html/varnish-dashboard/varnish-dashboard/index.html` by mistake.
