### ISSUE TITLE
Redirection from old Dashboard

### ISSUE THREAD

**Issue by pbruna** [brandonwamboldt/varnish-dashboard#6]
Hi,
First **great job**. 

Second, a lot of people ask me about updates on my Dashboard, but Im not working on that anymore. Would be ok with you if update the Readme to redirect the people here?

Thanks.

PS: https://github.com/ITLinuxCL/Varnish-Agent-Dashboard

**Comment by brandonwamboldt** [comment]
OMG It would be awesome if you update your readme to redirect people here! Thanks!
